#!/usr/bin/env python3
"""Generate the REFERENCE Postman collection from the partner spec.

Two collections live in integrations/, and they are not redundant:

  * legiscore.postman_collection.json is the guided flow, hand-written and ordered the
    way a partner actually integrates. It is the one you send. It covers the happy path.
  * legiscore-reference.postman_collection.json is this one: every operation in the spec,
    grouped by module, regenerated so it cannot drift. It is the one you look things up in.

The split mirrors the SDKs, where the method surface is generated and the helpers are
hand-written. Both collections share integrations/legiscore.postman_environment.json.

    python3 build_spec.py && python3 generate_clients.py && python3 build_postman.py

`--check` fails when the committed file no longer matches the spec, which is what CI runs.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

SPEC_PATH = Path(__file__).with_name("legiscore-openapi.json")
SDK_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = SDK_ROOT / "integrations"
COLLECTION_PATH = OUT_DIR / "legiscore-reference.postman_collection.json"

BANNER = "Generated by spec/build_postman.py from legiscore-openapi.json. Do not edit by hand."
SCHEMA_URL = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"

# Postman renders these as {{name}} and resolves them per environment. Path ids become
# variables rather than literals so one case id drives every request in the reports folder.
PATH_VARIABLE_HINTS = {
    "case_id": "A case id from POST /api/requests.",
    "job_id": "A raw-search or property-extraction job id.",
    "session_id": "A translation session id from POST /api/v1/translate/submit.",
    "slot_index": "The position of a slot in the missing-documents list, starting at 0.",
    "webhook_id": "The id of one of your registered webhooks.",
    "state": "A state slug, e.g. telangana.",
    "dimension": "A lookup dimension name from the catalog.",
}


def example_for(schema: dict[str, Any], spec: dict[str, Any], depth: int = 0) -> Any:
    """A placeholder value a partner can edit, not a valid request. Types over guesses."""
    if not schema or depth > 3:
        return None
    if "$ref" in schema:
        return example_for(resolve(schema["$ref"], spec), spec, depth)
    if "default" in schema:
        return schema["default"]
    if schema.get("enum"):
        return schema["enum"][0]
    # anyOf is how the spec writes "optional": take the first non-null branch.
    for branch in schema.get("anyOf", []):
        if branch.get("type") != "null":
            return example_for(branch, spec, depth)

    kind = schema.get("type")
    if kind == "array":
        item = example_for(schema.get("items", {}), spec, depth + 1)
        return [item] if item is not None else []
    if kind == "object" or "properties" in schema:
        return {
            name: example_for(prop, spec, depth + 1)
            for name, prop in schema.get("properties", {}).items()
        }
    return {"string": "", "integer": 0, "number": 0, "boolean": False}.get(kind)


def resolve(ref: str, spec: dict[str, Any]) -> dict[str, Any]:
    return spec["components"]["schemas"].get(ref.rsplit("/", 1)[-1], {})


def describe(parameter: dict[str, Any]) -> str:
    schema = parameter.get("schema", {})
    kind = schema.get("type") or next(
        (branch.get("type") for branch in schema.get("anyOf", []) if branch.get("type") != "null"),
        "string",
    )
    parts = [kind, "required" if parameter.get("required") else "optional"]
    if "default" in schema:
        parts.append(f"default {schema['default']}")
    return ", ".join(parts)


def build_request(method: str, path: str, operation: dict[str, Any], spec: dict[str, Any]) -> dict[str, Any]:
    templated = re.sub(r"\{(\w+)\}", r"{{\1}}", path)
    query = [p for p in operation.get("parameters", []) if p["in"] == "query"]
    url: dict[str, Any] = {
        "raw": "{{base_url}}" + templated + ("?" + "&".join(f"{p['name']}=" for p in query) if query else ""),
        "host": ["{{base_url}}"],
        "path": [segment for segment in templated.split("/") if segment],
    }
    if query:
        url["query"] = [
            {
                "key": parameter["name"],
                "value": str(parameter.get("schema", {}).get("default", "")),
                # Disabled so a fresh request sends none of them; Postman would otherwise
                # send every optional filter as an empty string.
                "disabled": True,
                "description": describe(parameter),
            }
            for parameter in query
        ]

    request: dict[str, Any] = {
        "method": method.upper(),
        "header": [],
        "url": url,
        "description": operation.get("description") or operation.get("summary", ""),
    }

    content = operation.get("requestBody", {}).get("content", {})
    if "application/json" in content:
        body = example_for(content["application/json"].get("schema", {}), spec)
        request["header"].append({"key": "Content-Type", "value": "application/json"})
        request["body"] = {
            "mode": "raw",
            "raw": json.dumps(body if body is not None else {}, indent=2),
            "options": {"raw": {"language": "json"}},
        }
    elif "multipart/form-data" in content:
        schema = content["multipart/form-data"].get("schema", {})
        properties = (resolve(schema["$ref"], spec) if "$ref" in schema else schema).get("properties", {})
        request["body"] = {
            "mode": "formdata",
            "formdata": [
                {"key": name, "type": "file" if prop.get("format") == "binary" else "text", "value": ""}
                if prop.get("format") == "binary"
                else {"key": name, "type": "text", "value": str(prop.get("default", ""))}
                for name, prop in properties.items()
            ],
        }
    return request


def build_collection(spec: dict[str, Any]) -> dict[str, Any]:
    folders: dict[str, dict[str, Any]] = {
        tag["name"]: {"name": tag["name"], "description": tag.get("description", ""), "item": []}
        for tag in spec.get("tags", [])
    }
    for path, methods in spec["paths"].items():
        for method, operation in methods.items():
            module = (operation.get("tags") or ["other"])[0]
            folder = folders.setdefault(module, {"name": module, "item": []})
            folder["item"].append(
                {"name": operation.get("summary") or operation["operationId"], "request": build_request(method, path, operation, spec)}
            )

    used_ids = sorted({name for path in spec["paths"] for name in re.findall(r"\{(\w+)\}", path)})
    scheme = spec["components"]["securitySchemes"]["ApiKeyHeader"]
    return {
        "info": {
            "name": f"{spec['info']['title']}: reference",
            "description": (
                f"{BANNER}\n\nEvery operation the partner API exposes, grouped by module. "
                "For the order you actually integrate in, use the guided collection beside this "
                f"one.\n\n{spec['info']['description']}"
            ),
            "schema": SCHEMA_URL,
        },
        # Collection-level, so every request inherits it and no folder can forget the key.
        "auth": {
            "type": "apikey",
            "apikey": [
                {"key": "key", "value": scheme["name"], "type": "string"},
                {"key": "value", "value": "{{api_key}}", "type": "string"},
                {"key": "in", "value": "header", "type": "string"},
            ],
        },
        "variable": [
            {"key": "base_url", "value": spec["servers"][0]["url"], "type": "string"},
            *[
                {"key": name, "value": "", "type": "string", "description": PATH_VARIABLE_HINTS.get(name, "")}
                for name in used_ids
            ],
        ],
        "item": [folders[tag["name"]] for tag in spec.get("tags", []) if folders.get(tag["name"], {}).get("item")],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    spec = json.loads(SPEC_PATH.read_text())
    collection = build_collection(spec)
    rendered = json.dumps(collection, indent=2) + "\n"

    if args.check:
        if not COLLECTION_PATH.exists() or COLLECTION_PATH.read_text() != rendered:
            print(f"{COLLECTION_PATH.name} is stale: the spec changed. Run build_postman.py.")
            return 1
        print("Reference Postman collection is current.")
        return 0

    OUT_DIR.mkdir(exist_ok=True)
    COLLECTION_PATH.write_text(rendered)
    summary = ", ".join(f"{folder['name']} {len(folder['item'])}" for folder in collection["item"])
    print(f"Wrote {COLLECTION_PATH.name}: {summary}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
