#!/usr/bin/env python3
"""Generate the per-module method surface of both SDKs from the partner spec.

Only the boring part is generated: one method per operation, grouped into module
namespaces. The transport, retries, errors and multi-step helpers are hand-written
in each package. Adding an endpoint is a one-line edit to build_spec.py followed by:

    python3 build_spec.py && python3 generate_clients.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

SPEC_PATH = Path(__file__).with_name("legiscore-openapi.json")
SDK_ROOT = Path(__file__).resolve().parent.parent
PYTHON_OUT = SDK_ROOT / "python" / "legiscore" / "_operations.py"
NODE_OUT = SDK_ROOT / "node" / "src" / "operations.ts"

BANNER = "Generated by spec/generate_clients.py. Do not edit by hand."
# The Python output is checked by `ruff format --check`, so it has to be split the way the
# formatter would split it rather than left as one long line.
PYTHON_LINE_LENGTH = 100
PYTHON_CONTINUATION_INDENT = 4


def snake_case(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def load_operations() -> dict[str, list[dict]]:
    """Group the spec's operations by module tag, preserving spec order."""
    spec = json.loads(SPEC_PATH.read_text())
    modules: dict[str, list[dict]] = {}
    for path, methods in spec["paths"].items():
        for method, operation in methods.items():
            content = operation.get("requestBody", {}).get("content", {})
            body_schema = (
                content.get("application/json", {}).get("schema", {}).get("$ref", "").rsplit("/", 1)[-1]
            )
            # A few endpoints take file uploads, not JSON. They need a different
            # request shape, so the generator has to know which ones.
            multipart_ref = (
                content.get("multipart/form-data", {}).get("schema", {}).get("$ref", "").rsplit("/", 1)[-1]
            )
            multipart_props = (
                spec["components"]["schemas"].get(multipart_ref, {}).get("properties", {})
                if multipart_ref
                else {}
            )
            file_fields = sorted(
                name
                for name, field in multipart_props.items()
                if field.get("format") == "binary" or field.get("items", {}).get("format") == "binary"
            )
            modules.setdefault(operation["tags"][0], []).append(
                {
                    "id": operation["operationId"],
                    "method": method.upper(),
                    "path": path,
                    "summary": (operation.get("summary") or operation["operationId"]).strip(),
                    "path_params": re.findall(r"\{(\w+)\}", path),
                    "body": body_schema,
                    "multipart": bool(multipart_ref),
                    "file_fields": file_fields,
                    "form_fields": sorted(set(multipart_props) - set(file_fields)),
                    "body_fields": sorted(
                        spec["components"]["schemas"].get(body_schema, {}).get("properties", {})
                    ),
                    "query_params": [
                        p["name"] for p in operation.get("parameters", []) if p.get("in") == "query"
                    ],
                }
            )
    return dict(sorted(modules.items()))


def describe(operation: dict) -> list[str]:
    lines = [operation["summary"], "", f"{operation['method']} {operation['path']}"]
    if operation["multipart"]:
        lines += ["", f"Files: {', '.join(operation['file_fields']) or 'none'}"]
        if operation["form_fields"]:
            lines += [f"Form: {', '.join(operation['form_fields'])}"]
    if operation["body_fields"]:
        shown = ", ".join(operation["body_fields"][:14])
        extra = "" if len(operation["body_fields"]) <= 14 else ", ..."
        lines += ["", f"Body ({operation['body']}): {shown}{extra}"]
    if operation["query_params"]:
        lines += ["", f"Query: {', '.join(operation['query_params'])}"]
    return lines


def wrap_python_parens(indent: str, head: str, items: list[str], tail: str) -> list[str]:
    """Split ``head(items)tail`` the way the Python formatter would.

    One line if it fits; otherwise the items on a single indented line; otherwise one item per
    line with a trailing comma, which is what keeps the formatter from re-joining them.
    """
    inline = f"{indent}{head}({', '.join(items)}){tail}"
    if len(inline) <= PYTHON_LINE_LENGTH:
        return [inline]
    inner = " " * (len(indent) + PYTHON_CONTINUATION_INDENT)
    joined = ", ".join(items)
    if len(inner) + len(joined) <= PYTHON_LINE_LENGTH:
        return [f"{indent}{head}(", f"{inner}{joined}", f"{indent}){tail}"]
    return [f"{indent}{head}(", *(f"{inner}{item}," for item in items), f"{indent}){tail}"]


def python_path_expression(operation: dict) -> str:
    """The URL literal for one operation, with any path parameters percent-encoded."""
    if not operation["path_params"]:
        return '"' + operation["path"] + '"'
    # quote(..., safe="") so an id containing / ? # or .. cannot re-target the request.
    encoded = operation["path"]
    for name in operation["path_params"]:
        encoded = encoded.replace("{" + name + "}", "{quote(str(" + name + "), safe='')}")
    return 'f"' + encoded + '"'


def render_python_method(operation: dict, *, is_async: bool) -> list[str]:
    """One generated method, in either the blocking or the awaited flavour."""
    params = ["self", *(f"{name}: str" for name in operation["path_params"])]
    if operation["multipart"]:
        params += ["files: dict[str, Any] | None = None", "**form: Any"]
    else:
        if operation["body"]:
            params.append("body: dict[str, Any] | None = None")
        params.append("**query: Any")

    keyword = "async def" if is_async else "def"
    lines = wrap_python_parens(
        "    ", f"{keyword} {snake_case(operation['id'])}", params, " -> Any:"
    )

    documentation = describe(operation)
    lines.append('        """' + documentation[0])
    for line in documentation[1:]:
        lines.append(f"        {line}" if line else "")
    lines.append('        """')

    awaited = "await " if is_async else ""
    method = json.dumps(operation["method"])
    path_expr = python_path_expression(operation)
    if operation["multipart"]:
        head = f"return {awaited}self._transport.request_multipart"
        args = [method, path_expr, "files=files", "form=form"]
    else:
        head = f"return {awaited}self._transport.request"
        args = [method, path_expr]
        if operation["body"]:
            args.append("body=body")
        args.append("query=query")
    return [*lines, *wrap_python_parens("        ", head, args, ""), ""]


def render_python(modules: dict[str, list[dict]]) -> str:
    out = [
        f'"""{BANNER}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "from urllib.parse import quote",
        "",
        "from ._transport import AsyncTransport, Transport",
        "",
        "",
        "class _Namespace:",
        "    def __init__(self, transport: Transport) -> None:",
        "        self._transport = transport",
        "",
        "",
        "class _AsyncNamespace:",
        "    def __init__(self, transport: AsyncTransport) -> None:",
        "        self._transport = transport",
        "",
    ]
    for module, operations in modules.items():
        name = module.title()
        # Every module ships twice: the blocking namespace and its awaited twin, same names.
        out += ["", f"class {name}Operations(_Namespace):", f'    """{module} endpoints."""', ""]
        for op in operations:
            out += render_python_method(op, is_async=False)
        out += [
            "",
            f"class Async{name}Operations(_AsyncNamespace):",
            f'    """{module} endpoints, awaited."""',
            "",
        ]
        for op in operations:
            out += render_python_method(op, is_async=True)
    return "\n".join(out).rstrip() + "\n"


def render_typescript(modules: dict[str, list[dict]]) -> str:
    out = [
        f"// {BANNER}",
        "",
        # .js extensions: the ESM build is emitted with moduleResolution NodeNext, which
        # requires them, and the CommonJS build resolves them just the same.
        'import type { RequestOptions, Transport, UploadFile } from "./transport.js";',
        "",
        "type Query = Record<string, string | number | boolean | undefined>;",
        "",
    ]
    for module, operations in modules.items():
        out += [f"export class {module[0].upper() + module[1:]}Operations {{",
                "  constructor(private readonly transport: Transport) {}",
                ""]
        for op in operations:
            args = [f"{p}: string" for p in op["path_params"]]
            if op["multipart"]:
                args.append("files?: Record<string, UploadFile | UploadFile[]>")
                args.append("form?: Record<string, string | number | boolean>")
            else:
                if op["body"]:
                    args.append("body?: Record<string, unknown>")
                args.append("query?: Query")
            # Every call takes an AbortSignal, so a Next.js request can cancel its own work.
            args.append("options?: RequestOptions")
            out.append("  /**")
            for line in describe(op):
                out.append(f"   * {line}".rstrip())
            out.append("   */")
            out.append(f"  async {op['id']}({', '.join(args)}): Promise<unknown> {{")
            path_expr = "`" + re.sub(r"\{(\w+)\}", r"${encodeURIComponent(\1)}", op["path"]) + "`"
            if op["multipart"]:
                call = (
                    f"    return this.transport.requestMultipart({json.dumps(op['method'])}, "
                    f"{path_expr}, files, form, options);"
                )
            else:
                call = f"    return this.transport.request({json.dumps(op['method'])}, {path_expr}, "
                call += "{ body, query, ...options });" if op["body"] else "{ query, ...options });"
            out += [call, "  }", ""]
        out += ["}", ""]
    return "\n".join(out)


def main() -> None:
    modules = load_operations()
    for target, rendered in ((PYTHON_OUT, render_python(modules)), (NODE_OUT, render_typescript(modules))):
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
    total = sum(len(ops) for ops in modules.values())
    print(f"Generated {total} methods across {len(modules)} modules -> {PYTHON_OUT.name}, {NODE_OUT.name}")


if __name__ == "__main__":
    main()
