// Generated by spec/generate_clients.py. Do not edit by hand.

import type { RequestOptions, Transport, UploadFile } from "./transport.js";

type Query = Record<string, string | number | boolean | undefined>;

export class CoreOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * List scenarios
   *
   * GET /api/scenarios
   *
   * Query: category, state_id
   */
  async listScenarios(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/scenarios`, { query, ...options });
  }

  /**
   * Get your credit balance
   *
   * GET /api/v1/credits
   */
  async getCredits(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/credits`, { query, ...options });
  }

  /**
   * List custom field configurations
   *
   * GET /api/v1/custom-field-configs
   */
  async listCustomFieldConfigs(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/custom-field-configs`, { query, ...options });
  }

  /**
   * Complete an upload
   *
   * POST /api/v1/uploads/complete
   *
   * Body (CompleteUploadRequest): contentType, content_hash, fileName, fileSize, objectName, page_count, success
   */
  async completeUpload(body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/v1/uploads/complete`, { body, query, ...options });
  }

  /**
   * Presign an upload
   *
   * POST /api/v1/uploads/presign
   *
   * Body (PresignUploadRequest): contentType, fileName, fileSize
   */
  async presignUpload(body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/v1/uploads/presign`, { body, query, ...options });
  }

}

export class ExtractionOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * Create a property extraction job
   *
   * POST /api/v1/extraction/property
   *
   * Files: files
   * Form: additional_context, available_checks, state_id, state_name, unified_search_schema
   */
  async createPropertyExtraction(files?: Record<string, UploadFile | UploadFile[]>, form?: Record<string, string | number | boolean>, options?: RequestOptions): Promise<unknown> {
    return this.transport.requestMultipart("POST", `/api/v1/extraction/property`, files, form, options);
  }

  /**
   * Get a property extraction job
   *
   * GET /api/v1/extraction/property/{job_id}
   */
  async getPropertyExtraction(job_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/extraction/property/${encodeURIComponent(job_id)}`, { query, ...options });
  }

}

export class ReportsOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * Read the risk-acknowledgement pause
   *
   * GET /api/cases/{case_id}/acknowledgements
   */
  async getAcknowledgements(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/acknowledgements`, { query, ...options });
  }

  /**
   * Answer the missing-documents pause
   *
   * POST /api/cases/{case_id}/continue
   *
   * Body (ContinueCaseRequest): document_annotations, new_document_ids, proceed_anyway, split_document_ids
   */
  async continueCase(case_id: string, body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/cases/${encodeURIComponent(case_id)}/continue`, { body, query, ...options });
  }

  /**
   * Read the document-analysis pause
   *
   * GET /api/cases/{case_id}/document-review
   */
  async getDocumentReview(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/document-review`, { query, ...options });
  }

  /**
   * List case files
   *
   * GET /api/cases/{case_id}/files
   *
   * Query: kinds
   */
  async listCaseFiles(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/files`, { query, ...options });
  }

  /**
   * Download all case files as a ZIP
   *
   * GET /api/cases/{case_id}/files/zip
   *
   * Query: kinds
   */
  async downloadCaseFilesZip(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/files/zip`, { query, ...options });
  }

  /**
   * Read the missing-documents pause
   *
   * GET /api/cases/{case_id}/missing-documents
   */
  async getMissingDocuments(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/missing-documents`, { query, ...options });
  }

  /**
   * Link documents to a missing-documents slot
   *
   * PATCH /api/cases/{case_id}/missing-documents/{slot_index}/link
   *
   * Body (LinkDocumentsToSlotRequest): document_ids, slot_id
   */
  async linkDocumentsToMissingSlot(case_id: string, slot_index: string, body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("PATCH", `/api/cases/${encodeURIComponent(case_id)}/missing-documents/${encodeURIComponent(slot_index)}/link`, { body, query, ...options });
  }

  /**
   * Get the final report
   *
   * GET /api/cases/{case_id}/result
   */
  async getCaseResult(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/result`, { query, ...options });
  }

  /**
   * Get case status
   *
   * GET /api/cases/{case_id}/status
   */
  async getCaseStatus(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/cases/${encodeURIComponent(case_id)}/status`, { query, ...options });
  }

  /**
   * Answer the risk-acknowledgement pause
   *
   * POST /api/cases/{case_id}/submit-acknowledgements
   *
   * Body (SubmitAcknowledgementsRequest): acknowledgements
   */
  async submitAcknowledgements(case_id: string, body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/cases/${encodeURIComponent(case_id)}/submit-acknowledgements`, { body, query, ...options });
  }

  /**
   * Answer the document-analysis pause
   *
   * POST /api/cases/{case_id}/submit-document-review
   *
   * Body (SubmitDocumentReviewRequest): proceed_to_searches, updates
   */
  async submitDocumentReview(case_id: string, body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/cases/${encodeURIComponent(case_id)}/submit-document-review`, { body, query, ...options });
  }

  /**
   * Create a case
   *
   * POST /api/requests
   *
   * Body (CreateCaseRequest): case_name, credit_source, credit_source_branch_id, credit_source_org_id, custom_field_schema_ids, custom_field_value_seed, documentIds, enableAcknowledgementReview, enableAnomalyReview, enableDocumentAnalysisReview, enableMissingDocumentReview, metadata, missing_document_seeds, payment_order_id, ...
   */
  async createCase(body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/requests`, { body, query, ...options });
  }

  /**
   * Download a case document
   *
   * GET /api/v1/documents/{case_id}
   *
   * Query: format
   */
  async getCaseDocuments(case_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/documents/${encodeURIComponent(case_id)}`, { query, ...options });
  }

}

export class SearchOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * Get the search catalog
   *
   * GET /api/v1/raw-search/catalog
   */
  async getSearchCatalog(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/catalog`, { query, ...options });
  }

  /**
   * List raw searches
   *
   * GET /api/v1/raw-search/history
   *
   * Query: limit, offset, state, search_type, status, include_extras
   */
  async listRawSearches(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/history`, { query, ...options });
  }

  /**
   * List lookup dimensions
   *
   * GET /api/v1/raw-search/lookups
   */
  async listLookupDimensions(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/lookups`, { query, ...options });
  }

  /**
   * Get lookup values
   *
   * GET /api/v1/raw-search/lookups/{state}/{dimension}
   */
  async getLookupValues(state: string, dimension: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/lookups/${encodeURIComponent(state)}/${encodeURIComponent(dimension)}`, { query, ...options });
  }

  /**
   * List searchable states
   *
   * GET /api/v1/raw-search/states
   */
  async listSearchStates(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/states`, { query, ...options });
  }

  /**
   * Get raw search status
   *
   * GET /api/v1/raw-search/status/{job_id}
   */
  async getRawSearchStatus(job_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/raw-search/status/${encodeURIComponent(job_id)}`, { query, ...options });
  }

  /**
   * Submit a raw search
   *
   * POST /api/v1/raw-search/submit
   *
   * Body (UnifiedRawSearchRequest): credit_source, credit_source_branch_id, credit_source_org_id, force, param_labels, params, payment_order_id, search_type, state
   */
  async submitRawSearch(body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/v1/raw-search/submit`, { body, query, ...options });
  }

}

export class TranslateOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * Translate a DOCX
   *
   * POST /api/v1/docx-translate
   *
   * Files: file
   * Form: backend, target_lang
   */
  async translateDocx(files?: Record<string, UploadFile | UploadFile[]>, form?: Record<string, string | number | boolean>, options?: RequestOptions): Promise<unknown> {
    return this.transport.requestMultipart("POST", `/api/v1/docx-translate`, files, form, options);
  }

  /**
   * List translation languages
   *
   * GET /api/v1/docx-translate/languages
   */
  async listTranslationLanguages(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/docx-translate/languages`, { query, ...options });
  }

  /**
   * Download a translation
   *
   * GET /api/v1/translate/download/{session_id}
   */
  async downloadTranslation(session_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/translate/download/${encodeURIComponent(session_id)}`, { query, ...options });
  }

  /**
   * List translations
   *
   * GET /api/v1/translate/history
   *
   * Query: limit, offset
   */
  async listTranslations(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/translate/history`, { query, ...options });
  }

  /**
   * Get translation status
   *
   * GET /api/v1/translate/status/{session_id}
   */
  async getTranslationStatus(session_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/translate/status/${encodeURIComponent(session_id)}`, { query, ...options });
  }

  /**
   * Submit a document for translation
   *
   * POST /api/v1/translate/submit
   *
   * Files: pdf
   * Form: billing_email, billing_name, billing_phone, credit_source, credit_source_branch_id, credit_source_org_id, payment_order_id, total_pages, user_id
   */
  async submitTranslation(files?: Record<string, UploadFile | UploadFile[]>, form?: Record<string, string | number | boolean>, options?: RequestOptions): Promise<unknown> {
    return this.transport.requestMultipart("POST", `/api/v1/translate/submit`, files, form, options);
  }

}

export class WebhooksOperations {
  constructor(private readonly transport: Transport) {}

  /**
   * List webhooks
   *
   * GET /api/v1/webhooks
   */
  async listWebhooks(query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("GET", `/api/v1/webhooks`, { query, ...options });
  }

  /**
   * Create a webhook
   *
   * POST /api/v1/webhooks
   *
   * Body (WebhookCreateRequest): custom_headers, events, name, url
   */
  async createWebhook(body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/v1/webhooks`, { body, query, ...options });
  }

  /**
   * Update a webhook
   *
   * PATCH /api/v1/webhooks/{webhook_id}
   *
   * Body (WebhookUpdateRequest): custom_headers, events, is_active, name, url
   */
  async updateWebhook(webhook_id: string, body?: Record<string, unknown>, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("PATCH", `/api/v1/webhooks/${encodeURIComponent(webhook_id)}`, { body, query, ...options });
  }

  /**
   * Delete a webhook
   *
   * DELETE /api/v1/webhooks/{webhook_id}
   */
  async deleteWebhook(webhook_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("DELETE", `/api/v1/webhooks/${encodeURIComponent(webhook_id)}`, { query, ...options });
  }

  /**
   * Rotate a webhook secret
   *
   * POST /api/v1/webhooks/{webhook_id}/rotate-secret
   */
  async rotateWebhookSecret(webhook_id: string, query?: Query, options?: RequestOptions): Promise<unknown> {
    return this.transport.request("POST", `/api/v1/webhooks/${encodeURIComponent(webhook_id)}/rotate-secret`, { query, ...options });
  }

}
