"""Generated by spec/generate_clients.py. Do not edit by hand."""

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from ._transport import AsyncTransport, Transport


class _Namespace:
    def __init__(self, transport: Transport) -> None:
        self._transport = transport


class _AsyncNamespace:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport


class CoreOperations(_Namespace):
    """core endpoints."""

    def list_scenarios(self, **query: Any) -> Any:
        """List scenarios

        GET /api/scenarios

        Query: category, state_id
        """
        return self._transport.request("GET", "/api/scenarios", query=query)

    def get_credits(self, **query: Any) -> Any:
        """Get your credit balance

        GET /api/v1/credits
        """
        return self._transport.request("GET", "/api/v1/credits", query=query)

    def list_custom_field_configs(self, **query: Any) -> Any:
        """List custom field configurations

        GET /api/v1/custom-field-configs
        """
        return self._transport.request("GET", "/api/v1/custom-field-configs", query=query)

    def complete_upload(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Complete an upload

        POST /api/v1/uploads/complete

        Body (CompleteUploadRequest): contentType, content_hash, fileName, fileSize, objectName, page_count, success
        """
        return self._transport.request("POST", "/api/v1/uploads/complete", body=body, query=query)

    def presign_upload(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Presign an upload

        POST /api/v1/uploads/presign

        Body (PresignUploadRequest): contentType, fileName, fileSize
        """
        return self._transport.request("POST", "/api/v1/uploads/presign", body=body, query=query)


class AsyncCoreOperations(_AsyncNamespace):
    """core endpoints, awaited."""

    async def list_scenarios(self, **query: Any) -> Any:
        """List scenarios

        GET /api/scenarios

        Query: category, state_id
        """
        return await self._transport.request("GET", "/api/scenarios", query=query)

    async def get_credits(self, **query: Any) -> Any:
        """Get your credit balance

        GET /api/v1/credits
        """
        return await self._transport.request("GET", "/api/v1/credits", query=query)

    async def list_custom_field_configs(self, **query: Any) -> Any:
        """List custom field configurations

        GET /api/v1/custom-field-configs
        """
        return await self._transport.request("GET", "/api/v1/custom-field-configs", query=query)

    async def complete_upload(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Complete an upload

        POST /api/v1/uploads/complete

        Body (CompleteUploadRequest): contentType, content_hash, fileName, fileSize, objectName, page_count, success
        """
        return await self._transport.request(
            "POST", "/api/v1/uploads/complete", body=body, query=query
        )

    async def presign_upload(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Presign an upload

        POST /api/v1/uploads/presign

        Body (PresignUploadRequest): contentType, fileName, fileSize
        """
        return await self._transport.request(
            "POST", "/api/v1/uploads/presign", body=body, query=query
        )


class ExtractionOperations(_Namespace):
    """extraction endpoints."""

    def create_property_extraction(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Create a property extraction job

        POST /api/v1/extraction/property

        Files: files
        Form: additional_context, available_checks, state_id, state_name, unified_search_schema
        """
        return self._transport.request_multipart(
            "POST", "/api/v1/extraction/property", files=files, form=form
        )

    def get_property_extraction(self, job_id: str, **query: Any) -> Any:
        """Get a property extraction job

        GET /api/v1/extraction/property/{job_id}
        """
        return self._transport.request(
            "GET", f"/api/v1/extraction/property/{quote(str(job_id), safe='')}", query=query
        )


class AsyncExtractionOperations(_AsyncNamespace):
    """extraction endpoints, awaited."""

    async def create_property_extraction(
        self, files: dict[str, Any] | None = None, **form: Any
    ) -> Any:
        """Create a property extraction job

        POST /api/v1/extraction/property

        Files: files
        Form: additional_context, available_checks, state_id, state_name, unified_search_schema
        """
        return await self._transport.request_multipart(
            "POST", "/api/v1/extraction/property", files=files, form=form
        )

    async def get_property_extraction(self, job_id: str, **query: Any) -> Any:
        """Get a property extraction job

        GET /api/v1/extraction/property/{job_id}
        """
        return await self._transport.request(
            "GET", f"/api/v1/extraction/property/{quote(str(job_id), safe='')}", query=query
        )


class ReportsOperations(_Namespace):
    """reports endpoints."""

    def get_acknowledgements(self, case_id: str, **query: Any) -> Any:
        """Read the risk-acknowledgement pause

        GET /api/cases/{case_id}/acknowledgements
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/acknowledgements", query=query
        )

    def continue_case(self, case_id: str, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Answer the missing-documents pause

        POST /api/cases/{case_id}/continue

        Body (ContinueCaseRequest): document_annotations, new_document_ids, proceed_anyway, split_document_ids
        """
        return self._transport.request(
            "POST", f"/api/cases/{quote(str(case_id), safe='')}/continue", body=body, query=query
        )

    def get_document_review(self, case_id: str, **query: Any) -> Any:
        """Read the document-analysis pause

        GET /api/cases/{case_id}/document-review
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/document-review", query=query
        )

    def list_case_files(self, case_id: str, **query: Any) -> Any:
        """List case files

        GET /api/cases/{case_id}/files

        Query: kinds
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/files", query=query
        )

    def download_case_files_zip(self, case_id: str, **query: Any) -> Any:
        """Download all case files as a ZIP

        GET /api/cases/{case_id}/files/zip

        Query: kinds
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/files/zip", query=query
        )

    def get_missing_documents(self, case_id: str, **query: Any) -> Any:
        """Read the missing-documents pause

        GET /api/cases/{case_id}/missing-documents
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/missing-documents", query=query
        )

    def link_documents_to_missing_slot(
        self, case_id: str, slot_index: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Link documents to a missing-documents slot

        PATCH /api/cases/{case_id}/missing-documents/{slot_index}/link

        Body (LinkDocumentsToSlotRequest): document_ids, slot_id
        """
        return self._transport.request(
            "PATCH",
            f"/api/cases/{quote(str(case_id), safe='')}/missing-documents/{quote(str(slot_index), safe='')}/link",
            body=body,
            query=query,
        )

    def get_case_result(self, case_id: str, **query: Any) -> Any:
        """Get the final report

        GET /api/cases/{case_id}/result
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/result", query=query
        )

    def get_case_status(self, case_id: str, **query: Any) -> Any:
        """Get case status

        GET /api/cases/{case_id}/status
        """
        return self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/status", query=query
        )

    def submit_acknowledgements(
        self, case_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Answer the risk-acknowledgement pause

        POST /api/cases/{case_id}/submit-acknowledgements

        Body (SubmitAcknowledgementsRequest): acknowledgements
        """
        return self._transport.request(
            "POST",
            f"/api/cases/{quote(str(case_id), safe='')}/submit-acknowledgements",
            body=body,
            query=query,
        )

    def submit_document_review(
        self, case_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Answer the document-analysis pause

        POST /api/cases/{case_id}/submit-document-review

        Body (SubmitDocumentReviewRequest): proceed_to_searches, updates
        """
        return self._transport.request(
            "POST",
            f"/api/cases/{quote(str(case_id), safe='')}/submit-document-review",
            body=body,
            query=query,
        )

    def create_case(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Create a case

        POST /api/requests

        Body (CreateCaseRequest): case_name, credit_source, credit_source_branch_id, credit_source_org_id, custom_field_schema_ids, custom_field_value_seed, documentIds, enableAcknowledgementReview, enableAnomalyReview, enableDocumentAnalysisReview, enableMissingDocumentReview, metadata, missing_document_seeds, payment_order_id, ...
        """
        return self._transport.request("POST", "/api/requests", body=body, query=query)

    def get_case_documents(self, case_id: str, **query: Any) -> Any:
        """Download a case document

        GET /api/v1/documents/{case_id}

        Query: format
        """
        return self._transport.request(
            "GET", f"/api/v1/documents/{quote(str(case_id), safe='')}", query=query
        )


class AsyncReportsOperations(_AsyncNamespace):
    """reports endpoints, awaited."""

    async def get_acknowledgements(self, case_id: str, **query: Any) -> Any:
        """Read the risk-acknowledgement pause

        GET /api/cases/{case_id}/acknowledgements
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/acknowledgements", query=query
        )

    async def continue_case(
        self, case_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Answer the missing-documents pause

        POST /api/cases/{case_id}/continue

        Body (ContinueCaseRequest): document_annotations, new_document_ids, proceed_anyway, split_document_ids
        """
        return await self._transport.request(
            "POST", f"/api/cases/{quote(str(case_id), safe='')}/continue", body=body, query=query
        )

    async def get_document_review(self, case_id: str, **query: Any) -> Any:
        """Read the document-analysis pause

        GET /api/cases/{case_id}/document-review
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/document-review", query=query
        )

    async def list_case_files(self, case_id: str, **query: Any) -> Any:
        """List case files

        GET /api/cases/{case_id}/files

        Query: kinds
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/files", query=query
        )

    async def download_case_files_zip(self, case_id: str, **query: Any) -> Any:
        """Download all case files as a ZIP

        GET /api/cases/{case_id}/files/zip

        Query: kinds
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/files/zip", query=query
        )

    async def get_missing_documents(self, case_id: str, **query: Any) -> Any:
        """Read the missing-documents pause

        GET /api/cases/{case_id}/missing-documents
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/missing-documents", query=query
        )

    async def link_documents_to_missing_slot(
        self, case_id: str, slot_index: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Link documents to a missing-documents slot

        PATCH /api/cases/{case_id}/missing-documents/{slot_index}/link

        Body (LinkDocumentsToSlotRequest): document_ids, slot_id
        """
        return await self._transport.request(
            "PATCH",
            f"/api/cases/{quote(str(case_id), safe='')}/missing-documents/{quote(str(slot_index), safe='')}/link",
            body=body,
            query=query,
        )

    async def get_case_result(self, case_id: str, **query: Any) -> Any:
        """Get the final report

        GET /api/cases/{case_id}/result
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/result", query=query
        )

    async def get_case_status(self, case_id: str, **query: Any) -> Any:
        """Get case status

        GET /api/cases/{case_id}/status
        """
        return await self._transport.request(
            "GET", f"/api/cases/{quote(str(case_id), safe='')}/status", query=query
        )

    async def submit_acknowledgements(
        self, case_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Answer the risk-acknowledgement pause

        POST /api/cases/{case_id}/submit-acknowledgements

        Body (SubmitAcknowledgementsRequest): acknowledgements
        """
        return await self._transport.request(
            "POST",
            f"/api/cases/{quote(str(case_id), safe='')}/submit-acknowledgements",
            body=body,
            query=query,
        )

    async def submit_document_review(
        self, case_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Answer the document-analysis pause

        POST /api/cases/{case_id}/submit-document-review

        Body (SubmitDocumentReviewRequest): proceed_to_searches, updates
        """
        return await self._transport.request(
            "POST",
            f"/api/cases/{quote(str(case_id), safe='')}/submit-document-review",
            body=body,
            query=query,
        )

    async def create_case(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Create a case

        POST /api/requests

        Body (CreateCaseRequest): case_name, credit_source, credit_source_branch_id, credit_source_org_id, custom_field_schema_ids, custom_field_value_seed, documentIds, enableAcknowledgementReview, enableAnomalyReview, enableDocumentAnalysisReview, enableMissingDocumentReview, metadata, missing_document_seeds, payment_order_id, ...
        """
        return await self._transport.request("POST", "/api/requests", body=body, query=query)

    async def get_case_documents(self, case_id: str, **query: Any) -> Any:
        """Download a case document

        GET /api/v1/documents/{case_id}

        Query: format
        """
        return await self._transport.request(
            "GET", f"/api/v1/documents/{quote(str(case_id), safe='')}", query=query
        )


class SearchOperations(_Namespace):
    """search endpoints."""

    def submit_search(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Submit a search

        POST /api/v1/search

        Body (SubmitSearchRequest): label, params, search_type, searches, state
        """
        return self._transport.request(
            "POST", "/api/v1/search", body=body, query=query, base="search"
        )

    def list_searches(self, **query: Any) -> Any:
        """List your searches

        GET /api/v1/search

        Query: limit, offset, status, batch_id
        """
        return self._transport.request("GET", "/api/v1/search", query=query, base="search")

    def assist_search(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Propose search parameters from a document

        POST /api/v1/search/assist

        Files: file
        Form: state, text
        """
        return self._transport.request_multipart(
            "POST", "/api/v1/search/assist", files=files, form=form, base="search"
        )

    def get_search_catalog(self, **query: Any) -> Any:
        """Get the search catalog

        GET /api/v1/search/catalog

        Query: state
        """
        return self._transport.request("GET", "/api/v1/search/catalog", query=query, base="search")

    def get_search_credits(self, **query: Any) -> Any:
        """Get your search credit balance

        GET /api/v1/search/credits

        Query: limit
        """
        return self._transport.request("GET", "/api/v1/search/credits", query=query, base="search")

    def get_search_lookups(self, **query: Any) -> Any:
        """Resolve a lookup to its codes

        GET /api/v1/search/lookups

        Query: state, dim, q, district, mandal, limit
        """
        return self._transport.request("GET", "/api/v1/search/lookups", query=query, base="search")

    def get_search(self, search_id: str, **query: Any) -> Any:
        """Get one search

        GET /api/v1/search/{search_id}
        """
        return self._transport.request(
            "GET", f"/api/v1/search/{quote(str(search_id), safe='')}", query=query, base="search"
        )

    def cancel_search(self, search_id: str, **query: Any) -> Any:
        """Cancel a search

        DELETE /api/v1/search/{search_id}
        """
        return self._transport.request(
            "DELETE", f"/api/v1/search/{quote(str(search_id), safe='')}", query=query, base="search"
        )

    def get_search_document(self, search_id: str, filename: str, **query: Any) -> Any:
        """Download a document from a search

        GET /api/v1/search/{search_id}/documents/{filename}

        Returns bytes, not JSON. The API answers with a redirect to a short-lived
        signed URL, which the SDK follows for you without sending your API key.
        """
        return self._transport.request_download(
            "GET",
            f"/api/v1/search/{quote(str(search_id), safe='')}/documents/{quote(str(filename), safe='')}",
            query=query,
            base="search",
        )

    def submit_search_otp(
        self, search_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Supply a one-time password

        POST /api/v1/search/{search_id}/otp

        Body (SubmitSearchOtpRequest): otp
        """
        return self._transport.request(
            "POST",
            f"/api/v1/search/{quote(str(search_id), safe='')}/otp",
            body=body,
            query=query,
            base="search",
        )

    def recover_search(self, search_id: str, **query: Any) -> Any:
        """Recover an incomplete search

        POST /api/v1/search/{search_id}/recover
        """
        return self._transport.request(
            "POST",
            f"/api/v1/search/{quote(str(search_id), safe='')}/recover",
            query=query,
            base="search",
        )


class AsyncSearchOperations(_AsyncNamespace):
    """search endpoints, awaited."""

    async def submit_search(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Submit a search

        POST /api/v1/search

        Body (SubmitSearchRequest): label, params, search_type, searches, state
        """
        return await self._transport.request(
            "POST", "/api/v1/search", body=body, query=query, base="search"
        )

    async def list_searches(self, **query: Any) -> Any:
        """List your searches

        GET /api/v1/search

        Query: limit, offset, status, batch_id
        """
        return await self._transport.request("GET", "/api/v1/search", query=query, base="search")

    async def assist_search(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Propose search parameters from a document

        POST /api/v1/search/assist

        Files: file
        Form: state, text
        """
        return await self._transport.request_multipart(
            "POST", "/api/v1/search/assist", files=files, form=form, base="search"
        )

    async def get_search_catalog(self, **query: Any) -> Any:
        """Get the search catalog

        GET /api/v1/search/catalog

        Query: state
        """
        return await self._transport.request(
            "GET", "/api/v1/search/catalog", query=query, base="search"
        )

    async def get_search_credits(self, **query: Any) -> Any:
        """Get your search credit balance

        GET /api/v1/search/credits

        Query: limit
        """
        return await self._transport.request(
            "GET", "/api/v1/search/credits", query=query, base="search"
        )

    async def get_search_lookups(self, **query: Any) -> Any:
        """Resolve a lookup to its codes

        GET /api/v1/search/lookups

        Query: state, dim, q, district, mandal, limit
        """
        return await self._transport.request(
            "GET", "/api/v1/search/lookups", query=query, base="search"
        )

    async def get_search(self, search_id: str, **query: Any) -> Any:
        """Get one search

        GET /api/v1/search/{search_id}
        """
        return await self._transport.request(
            "GET", f"/api/v1/search/{quote(str(search_id), safe='')}", query=query, base="search"
        )

    async def cancel_search(self, search_id: str, **query: Any) -> Any:
        """Cancel a search

        DELETE /api/v1/search/{search_id}
        """
        return await self._transport.request(
            "DELETE", f"/api/v1/search/{quote(str(search_id), safe='')}", query=query, base="search"
        )

    async def get_search_document(self, search_id: str, filename: str, **query: Any) -> Any:
        """Download a document from a search

        GET /api/v1/search/{search_id}/documents/{filename}

        Returns bytes, not JSON. The API answers with a redirect to a short-lived
        signed URL, which the SDK follows for you without sending your API key.
        """
        return await self._transport.request_download(
            "GET",
            f"/api/v1/search/{quote(str(search_id), safe='')}/documents/{quote(str(filename), safe='')}",
            query=query,
            base="search",
        )

    async def submit_search_otp(
        self, search_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Supply a one-time password

        POST /api/v1/search/{search_id}/otp

        Body (SubmitSearchOtpRequest): otp
        """
        return await self._transport.request(
            "POST",
            f"/api/v1/search/{quote(str(search_id), safe='')}/otp",
            body=body,
            query=query,
            base="search",
        )

    async def recover_search(self, search_id: str, **query: Any) -> Any:
        """Recover an incomplete search

        POST /api/v1/search/{search_id}/recover
        """
        return await self._transport.request(
            "POST",
            f"/api/v1/search/{quote(str(search_id), safe='')}/recover",
            query=query,
            base="search",
        )


class TranslateOperations(_Namespace):
    """translate endpoints."""

    def translate_docx(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Translate a DOCX

        POST /api/v1/docx-translate

        Files: file
        Form: backend, target_lang
        """
        return self._transport.request_multipart(
            "POST", "/api/v1/docx-translate", files=files, form=form
        )

    def list_translation_languages(self, **query: Any) -> Any:
        """List translation languages

        GET /api/v1/docx-translate/languages
        """
        return self._transport.request("GET", "/api/v1/docx-translate/languages", query=query)

    def download_translation(self, session_id: str, **query: Any) -> Any:
        """Download a translation

        GET /api/v1/translate/download/{session_id}
        """
        return self._transport.request(
            "GET", f"/api/v1/translate/download/{quote(str(session_id), safe='')}", query=query
        )

    def list_translations(self, **query: Any) -> Any:
        """List translations

        GET /api/v1/translate/history

        Query: limit, offset
        """
        return self._transport.request("GET", "/api/v1/translate/history", query=query)

    def get_translation_status(self, session_id: str, **query: Any) -> Any:
        """Get translation status

        GET /api/v1/translate/status/{session_id}
        """
        return self._transport.request(
            "GET", f"/api/v1/translate/status/{quote(str(session_id), safe='')}", query=query
        )

    def submit_translation(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Submit a document for translation

        POST /api/v1/translate/submit

        Files: pdf
        Form: billing_email, billing_name, billing_phone, credit_source, credit_source_branch_id, credit_source_org_id, payment_order_id, total_pages, user_id
        """
        return self._transport.request_multipart(
            "POST", "/api/v1/translate/submit", files=files, form=form
        )


class AsyncTranslateOperations(_AsyncNamespace):
    """translate endpoints, awaited."""

    async def translate_docx(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Translate a DOCX

        POST /api/v1/docx-translate

        Files: file
        Form: backend, target_lang
        """
        return await self._transport.request_multipart(
            "POST", "/api/v1/docx-translate", files=files, form=form
        )

    async def list_translation_languages(self, **query: Any) -> Any:
        """List translation languages

        GET /api/v1/docx-translate/languages
        """
        return await self._transport.request("GET", "/api/v1/docx-translate/languages", query=query)

    async def download_translation(self, session_id: str, **query: Any) -> Any:
        """Download a translation

        GET /api/v1/translate/download/{session_id}
        """
        return await self._transport.request(
            "GET", f"/api/v1/translate/download/{quote(str(session_id), safe='')}", query=query
        )

    async def list_translations(self, **query: Any) -> Any:
        """List translations

        GET /api/v1/translate/history

        Query: limit, offset
        """
        return await self._transport.request("GET", "/api/v1/translate/history", query=query)

    async def get_translation_status(self, session_id: str, **query: Any) -> Any:
        """Get translation status

        GET /api/v1/translate/status/{session_id}
        """
        return await self._transport.request(
            "GET", f"/api/v1/translate/status/{quote(str(session_id), safe='')}", query=query
        )

    async def submit_translation(self, files: dict[str, Any] | None = None, **form: Any) -> Any:
        """Submit a document for translation

        POST /api/v1/translate/submit

        Files: pdf
        Form: billing_email, billing_name, billing_phone, credit_source, credit_source_branch_id, credit_source_org_id, payment_order_id, total_pages, user_id
        """
        return await self._transport.request_multipart(
            "POST", "/api/v1/translate/submit", files=files, form=form
        )


class WebhooksOperations(_Namespace):
    """webhooks endpoints."""

    def list_webhooks(self, **query: Any) -> Any:
        """List webhooks

        GET /api/v1/webhooks
        """
        return self._transport.request("GET", "/api/v1/webhooks", query=query)

    def create_webhook(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Create a webhook

        POST /api/v1/webhooks

        Body (WebhookCreateRequest): custom_headers, events, name, url
        """
        return self._transport.request("POST", "/api/v1/webhooks", body=body, query=query)

    def update_webhook(
        self, webhook_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Update a webhook

        PATCH /api/v1/webhooks/{webhook_id}

        Body (WebhookUpdateRequest): custom_headers, events, is_active, name, url
        """
        return self._transport.request(
            "PATCH", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}", body=body, query=query
        )

    def delete_webhook(self, webhook_id: str, **query: Any) -> Any:
        """Delete a webhook

        DELETE /api/v1/webhooks/{webhook_id}
        """
        return self._transport.request(
            "DELETE", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}", query=query
        )

    def rotate_webhook_secret(self, webhook_id: str, **query: Any) -> Any:
        """Rotate a webhook secret

        POST /api/v1/webhooks/{webhook_id}/rotate-secret
        """
        return self._transport.request(
            "POST", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}/rotate-secret", query=query
        )


class AsyncWebhooksOperations(_AsyncNamespace):
    """webhooks endpoints, awaited."""

    async def list_webhooks(self, **query: Any) -> Any:
        """List webhooks

        GET /api/v1/webhooks
        """
        return await self._transport.request("GET", "/api/v1/webhooks", query=query)

    async def create_webhook(self, body: dict[str, Any] | None = None, **query: Any) -> Any:
        """Create a webhook

        POST /api/v1/webhooks

        Body (WebhookCreateRequest): custom_headers, events, name, url
        """
        return await self._transport.request("POST", "/api/v1/webhooks", body=body, query=query)

    async def update_webhook(
        self, webhook_id: str, body: dict[str, Any] | None = None, **query: Any
    ) -> Any:
        """Update a webhook

        PATCH /api/v1/webhooks/{webhook_id}

        Body (WebhookUpdateRequest): custom_headers, events, is_active, name, url
        """
        return await self._transport.request(
            "PATCH", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}", body=body, query=query
        )

    async def delete_webhook(self, webhook_id: str, **query: Any) -> Any:
        """Delete a webhook

        DELETE /api/v1/webhooks/{webhook_id}
        """
        return await self._transport.request(
            "DELETE", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}", query=query
        )

    async def rotate_webhook_secret(self, webhook_id: str, **query: Any) -> Any:
        """Rotate a webhook secret

        POST /api/v1/webhooks/{webhook_id}/rotate-secret
        """
        return await self._transport.request(
            "POST", f"/api/v1/webhooks/{quote(str(webhook_id), safe='')}/rotate-secret", query=query
        )
